spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://www.zensolutions.com.br:3306/zensolutions_java?useTimezone=true&serverTimezone=UTC
      username: zensolutions_java
      password: vMgSKoz46X
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
      show-sql: false