name: CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./ApiPerson
      run: mvn clean package -DskipTests
      
    - name: Docker Compose Build
      working-directory: ./ApiPerson
      run: docker compose build
    
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_HUB_USER }}/rest-with-spring-boot-zensolution:latest ${{ secrets.DOCKER_HUB_USER }}/rest-with-spring-boot-zensolution:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/rest-with-spring-boot-zensolution:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/rest-with-spring-boot-zensolution:latest
        
